# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('quote', '0002_auto_20180305_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to='login.user'),
        ),
    ]
